# Generated by Django 2.2.7 on 2020-03-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responce', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responce',
        ),
    ]
